apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-kjsc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-kjsc
    app.kubernetes.io/part-of: test-app-810
  name: retrodep-kjsc
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-kjsc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-kjsc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-810/retrodep-kjsc@sha256:f90ffb38a51e5cf34f299cf59887291a2046827cbeed0cc95bc4678a3b0d698b
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
