apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-nhf2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-nhf2
    app.kubernetes.io/part-of: test-app-810
  name: nodejs-no-dockerfile-nhf2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-no-dockerfile-nhf2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-no-dockerfile-nhf2
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-810/nodejs-no-dockerfile-nhf2@sha256:154d2c83900aca10e9eac2dad8b0573c1af79cbb3dae6c59451bfada6dbf1fed
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
