apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pip-e2e-test-dj6g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pip-e2e-test-dj6g
    app.kubernetes.io/part-of: test-app-810
  name: pip-e2e-test-dj6g
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: pip-e2e-test-dj6g
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: pip-e2e-test-dj6g
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-810/pip-e2e-test-dj6g@sha256:183661350ee8709388995fe058033b8cc6b724caae51b03fefb5a8aca5a13c3a
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
